### PR TITLE
[rt_draw.c]: Fixing wrong cast, affecting the Apogee logo animation.

### LINKED ISSUE #18: Apogee logo rotation on startup is incorrect.
https://github.com/fabiangreffrath/rott/assets/76531574/4000186d-1c5b-4a2a-9be1-b4279cef3713

https://github.com/fabiangreffrath/rott/assets/76531574/570202e3-3d46-48bc-9380-d1666820349c

### PR DESCRIPTION
**Pull request by malespiaut**
Fixes #18

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Now this fixes the warnings. Could you please check if it fixes the animation as well? I can't, unfortunately, I'm at work right now.

**Comment by fabiangreffrath** [comment]
> I'm at work right now.

Which means I can write and commit code, but I have no chance to test-run the game in an office with ~20 other engineers. 😁

**Comment by malespiaut** [comment]
Hello Fabian,

I'll check that, right away.

**Comment by malespiaut** [comment]
That fixed it! Congratulations!

**Comment by fabiangreffrath** [comment]
> That fixed it! Congratulations!

Thanks! While at it, could you please check if #33 works as expected?

**Pull request merged**
